- name: Configurar de splunkforwarder
  ansible.builtin.expect:
    command: /root/splunkforwarder/bin/splunk enable --accept-license
    responses:
        "Please enter an administrator username:":
            - "sabarca@invoke.cl"
        "Please enter a new password:":
            - "{{ splunk_pass_encuesta }}"
        "Please confirm new password:":
            - "{{ splunk_pass_encuesta }}"